#include "../src/main.cpp"
#ifdef MAKE_GUI
#include "../src/fltk_gui.cpp"
#endif
#include "../src/attacks.cpp"
#include "../src/exmove.cpp"
#include "../src/swap.cpp"
#include "../src/moves.cpp"
#include "../src/captures.cpp"
#include "../src/captchecks.cpp"
#include "../src/hash.cpp"
#include "../src/smp.cpp"
#include "../src/search.cpp"
#include "../src/score.cpp"
#include "../src/check.cpp"
#include "../src/book.cpp"
#include "../src/sort.cpp"
#include "../src/util.cpp"
#include "../src/support.cpp"
#include "../src/probe.cpp"
#include "../src/setup.cpp"
#include "../src/game_rec.cpp"
#include "../src/tree_search_functions.cpp"

